name: Reusable linting workflow

on:
  workflow_call:

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff==0.1.2
      - name: Run Ruff
        run: ruff check --output-format=github .
